import type { AssessmentAgentSummary } from "@/lib/agent/summary";

function EvidenceList({
  title,
  items,
}: {
  title: string;
  items: AssessmentAgentSummary["establishedEvidence"];
}) {
  return (
    <section aria-labelledby={`summary-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}>
      <h3 id={`summary-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}>{title}</h3>
      {items.length ? (
        <ul>
          {items.map((item) => (
            <li key={item.id}>
              <strong>{item.label}</strong>
              {item.rationale ? <> — {item.rationale}</> : null}
            </li>
          ))}
        </ul>
      ) : (
        <p>None recorded.</p>
      )}
    </section>
  );
}

export function AgentSummary({ summary }: { summary: AssessmentAgentSummary }) {
  return (
    <section className="card stack" aria-labelledby="agent-summary-heading">
      <div>
        <p className="eyebrow">Evidence-based output</p>
        <h2 id="agent-summary-heading">BiasLens assessment summary</h2>
        <p>
          This summary separates what is established from what remains unknown or
          conflicted. It is not a binary bias or compliance verdict.
        </p>
      </div>

      <section aria-labelledby="summary-progress-heading">
        <h3 id="summary-progress-heading">Assessment progress</h3>
        <p>
          <strong>{summary.answeredCount}</strong> visible questions answered;{" "}
          <strong>{summary.remainingCount}</strong> remaining.
        </p>
      </section>

      <EvidenceList title="Established evidence" items={summary.establishedEvidence} />
      <EvidenceList title="Unknown evidence" items={summary.unknowns} />
      <EvidenceList title="Conflicted evidence" items={summary.conflicts} />

      <section aria-labelledby="summary-pathways-heading">
        <h3 id="summary-pathways-heading">Potential bias pathways</h3>
        {summary.potentialBiasPathways.length ? (
          <ul>
            {summary.potentialBiasPathways.map((pathway) => (
              <li key={`${pathway.title}-${pathway.rationale}`}>
                <strong>{pathway.title}</strong>
                <p>{pathway.rationale}</p>
                <p className="hint">
                  <strong>Limitation:</strong> {pathway.limitation}
                </p>
              </li>
            ))}
          </ul>
        ) : (
          <p>
            No evidence-grounded bias pathway has been added to this structured
            summary yet.
          </p>
        )}
      </section>

      <section aria-labelledby="summary-actions-heading">
        <h3 id="summary-actions-heading">Recommended next actions</h3>
        {summary.recommendedNextActions.length ? (
          <ul>
            {summary.recommendedNextActions.map((action) => (
              <li key={action}>{action}</li>
            ))}
          </ul>
        ) : (
          <p>No additional evidence action is currently generated by this summary.</p>
        )}
      </section>

      {summary.humanReviewRequired ? (
        <section className="form-error" aria-labelledby="summary-review-heading">
          <h3 id="summary-review-heading">Human review required</h3>
          <p>{summary.humanReviewReason}</p>
        </section>
      ) : null}

      <section aria-labelledby="summary-limitations-heading">
        <h3 id="summary-limitations-heading">Limitations</h3>
        <ul>
          {summary.limitations.map((limitation) => (
            <li key={limitation}>{limitation}</li>
          ))}
        </ul>
      </section>
    </section>
  );
}
